### ISSUE TITLE
Pouvez-vous retirer ce projet.

### ISSUE THREAD

**Issue by luctrudeau** [xeph/LOG540.TP1#1]
Pour éviter des problèmes de plagiat pouvez-vous retirer ce projet.

**Comment by xeph** [comment]
Le code a ete place dans un 7z avec mot de passe (AES-256) pour eviter le plagiat et pour garder mon travail.

**Comment by luctrudeau** [comment]
Github est un système de gestion de version, j'ai juste à revenir une version en arrière et j'ai le code.

Par exemple:
https://github.com/xeph/LOG540.TP1/tree/ca9fab6309185ebf4690a9f01517635b03ca69f1/src/com/grapeshot/halfnes
